// Builds the co-op data.win: imports mod/gml/*.gml and applies mod/hooks.txt.
// Run via tools/build.sh (UndertaleModCli load <vanilla> -s build.csx -o <out>).
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UndertaleModLib;
using UndertaleModLib.Models;

string root = Environment.GetEnvironmentVariable("COOP_ROOT") ?? @"C:\Users\pasha\zerosievert-coop";
string gmlDir = Path.Combine(root, "mod", "gml");
string hooksFile = Path.Combine(root, "mod", "hooks.txt");

// Extension functions the game never calls itself (e.g. Steam lobby/P2P) have no FUNC entry, so the
// compiler would treat calls to them as variable calls. Declare every one our code uses.
var modText = string.Join("\n", Directory.GetFiles(gmlDir, "*.gml").Select(File.ReadAllText));
int declared = 0;
foreach (var ext in Data.Extensions)
    foreach (var file in ext.Files)
        foreach (var fn in file.Functions)
        {
            string name = fn.Name.Content;
            if (System.Text.RegularExpressions.Regex.IsMatch(modText, @"\b" + name + @"\s*\(") && Data.Functions.ByName(name) == null)
            {
                Data.Functions.EnsureDefined(name, Data.Strings);
                declared++;
            }
        }
Console.WriteLine($"declared {declared} extension functions");

var group = new UndertaleModLib.Compiler.CodeImportGroup(Data)
{
    AutoCreateAssets = true,
    ThrowOnNoOpFindReplace = true
};

// UTMT's compiler does not share #macro across code entries: expand them textually here.
var sources = new Dictionary<string, string>();
var macros = new Dictionary<string, string>();
var macroRx = new System.Text.RegularExpressions.Regex(@"^#macro\s+(\w+)\s+(.+)$", System.Text.RegularExpressions.RegexOptions.Multiline);
// High refresh rate: objects with alarm events for coop_fps.gml. Generated first: a function is only
// visible to code compiled after it.
var alarmIdx = new Dictionary<UndertaleGameObject, SortedSet<uint>>();
foreach (var go in Data.GameObjects)
{
    if (go.Name.Content == "obj_coop") continue;
    foreach (var ev in go.Events[2])
    {
        if (!alarmIdx.ContainsKey(go)) alarmIdx[go] = new SortedSet<uint>();
        alarmIdx[go].Add(ev.EventSubtype);
    }
}
Func<UndertaleGameObject, UndertaleGameObject, bool> isAncestor = (anc, o) =>
{
    for (var p = o.ParentId; p != null && p != o; p = p.ParentId) if (p == anc) return true;
    return false;
};
// Alarm events an object really has (own or inherited): the runner does not count down an alarm without
// an event, so only those may be held.
var ownAlarms = new Dictionary<UndertaleGameObject, uint>();
foreach (var go in Data.GameObjects)
{
    if (go.Name.Content == "obj_coop") continue;
    uint m = 0;
    for (var o = go; o != null; o = (o.ParentId == o ? null : o.ParentId))
        foreach (var ev in o.Events[2]) m |= 1u << (int)ev.EventSubtype;
    if (m != 0) ownAlarms[go] = m;
}
var tabEntries = new List<string>();
var scanLines = new List<string>();
var holdLines = new List<string>();
Func<SortedSet<uint>, string> condOf = set => string.Join(" || ", set.Select(i => $"((_k & {1u << (int)i}) && alarm[{i}] > 0)"));
foreach (var go in alarmIdx.Keys)
{
    if (alarmIdx.Keys.Any(a => a != go && isAncestor(a, go))) continue; // covered by with(ancestor)
    var set = new SortedSet<uint>(alarmIdx[go]);
    foreach (var d in alarmIdx.Keys) if (isAncestor(go, d)) set.UnionWith(alarmIdx[d]);
    int k = tabEntries.Count;
    tabEntries.Add(go.Name.Content);
    scanLines.Add($"    _a = _l[{k}]; array_resize(_a, 0); with ({go.Name.Content}) {{ _k = _m[object_index]; if ({condOf(set)}) array_push(_a, id); }}");
    holdLines.Add($"    _a = _l[{k}]; _n = array_length(_a); for (_i = 0; _i < _n; _i++) with (_a[_i]) {{ _k = _m[object_index]; {string.Join(" ", set.Select(i => $"if ((_k & {1u << (int)i}) && alarm[{i}] > 0) alarm[{i}] += 1;"))} }}");
}
// One list per object family. zs_fps_alarm_scan: (end of each logic tick) instances with a running alarm.
// zs_fps_alarm_hold: (render-only frames) give them back the step the runner takes off.
string NL = "\n";
var maskLines = ownAlarms.Select(kv => $"    _m[{kv.Key.Name.Content}] = {kv.Value};");
sources["gml_GlobalScript_coop_fps_tables"] =
    "// Generated by build.csx from the objects with alarm events." + NL +
    "function zs_fps_alarm_lists()" + NL + "{" + NL + $"    var _l = array_create({tabEntries.Count});" + NL +
    $"    for (var _i = 0; _i < {tabEntries.Count}; _i++) _l[_i] = [];" + NL + "    return _l;" + NL + "}" + NL + NL +
    "function zs_fps_alarm_masks()" + NL + "{" + NL + $"    var _m = array_create({Data.GameObjects.Count + 1}, 0);" + NL + string.Join(NL, maskLines) + NL + "    return _m;" + NL + "}" + NL + NL +
    "function zs_fps_alarm_scan(_l, _m)" + NL + "{" + NL + "    var _a, _k;" + NL + string.Join(NL, scanLines) + NL + "}" + NL + NL +
    "function zs_fps_alarm_hold(_l, _m)" + NL + "{" + NL + "    var _a, _n, _i, _k;" + NL + string.Join(NL, holdLines) + NL + "}" + NL;
Console.WriteLine($"fps: alarm table {tabEntries.Count} objects");
foreach (string file in Directory.GetFiles(gmlDir, "*.gml").OrderBy(f => f))
{
    string text = File.ReadAllText(file).Replace("\r\n", "\n");
    foreach (System.Text.RegularExpressions.Match m in macroRx.Matches(text)) macros[m.Groups[1].Value] = m.Groups[2].Value.Trim();
    sources[Path.GetFileNameWithoutExtension(file)] = macroRx.Replace(text, "");
}
int files = 0;
foreach (var kv in sources)
{
    string text = kv.Value;
    for (int pass = 0; pass < 3; pass++)
        foreach (var m in macros)
            text = System.Text.RegularExpressions.Regex.Replace(text, @"\b" + m.Key + @"\b", m.Value);
    var left = System.Text.RegularExpressions.Regex.Match(text, @"\bCOOP_[A-Z0-9_]+\b");
    if (left.Success) throw new Exception($"unexpanded macro {left.Value} in {kv.Key}");
    group.QueueReplace(kv.Key, text);
    files++;
}

int hooks = 0;
string[] lines = File.ReadAllText(hooksFile).Replace("\r\n", "\n").Split('\n');
for (int i = 0; i < lines.Length; i++)
{
    if (!lines[i].StartsWith("### ")) continue;
    string[] head = lines[i].Substring(4).Split(' ');
    string op = head[0], code = head[1];
    var body = new List<string>();
    int j = i + 1;
    while (j < lines.Length && lines[j] != "<<<END") { body.Add(lines[j]); j++; }
    i = j;
    if (op == "findreplace")
    {
        int f = body.IndexOf("<<<FIND"), r = body.IndexOf("<<<REPLACE");
        string find = string.Join("\n", body.Skip(f + 1).Take(r - f - 1));
        string repl = string.Join("\n", body.Skip(r + 1));
        group.QueueFindReplace(code, find, repl, true);
    }
    else if (op == "prepend") group.QueuePrepend(code, string.Join("\n", body));
    else if (op == "append") group.QueueAppend(code, string.Join("\n", body));
    else throw new Exception("unknown hook op " + op);
    hooks++;
}

// High refresh rate (coop_fps.gml): the game's logic events exit on render-only frames. Alarms are not
// guarded (that would lose them) - they are held by obj_coop through the generated table (top of this file).
var guardRx = new System.Text.RegularExpressions.Regex(@"^gml_Object_(.+)_(Step_[012]|Collision_.+|Keyboard_\d+|KeyPress_\d+|KeyRelease_\d+|Mouse_\d+|Other_(0|1|4\d|5\d))$");
int guarded = 0;
foreach (var code in Data.Code.ToList())
{
    if (code.ParentEntry != null) continue;
    string cname = code.Name.Content;
    var gm = guardRx.Match(cname);
    if (!gm.Success || gm.Groups[1].Value == "obj_coop" || sources.ContainsKey(cname)) continue;
    group.QueuePrepend(cname, "if (global.zs_rfq && zs_rf_q()) exit;");
    guarded++;
}
Console.WriteLine($"fps: guarded {guarded} logic events");

// Debug builds only: COOP_TRACE_EVENTS=<regex over code entry names> prepends a phase marker (logged with
// -coop_phase) to those game events, to find where a freeze happens.
string traceRx = Environment.GetEnvironmentVariable("COOP_TRACE_EVENTS");
if (!string.IsNullOrEmpty(traceRx))
{
    var trx = new System.Text.RegularExpressions.Regex(traceRx);
    int traced = 0;
    foreach (var code in Data.Code.ToList())
    {
        if (code.ParentEntry != null) continue;
        string cname = code.Name.Content;
        if (!cname.StartsWith("gml_Object_") || cname.Contains("obj_coop") || sources.ContainsKey(cname) || !trx.IsMatch(cname)) continue;
        group.QueuePrepend(cname, "coop_phase(\"" + cname.Substring(11) + "\");");
        traced++;
    }
    Console.WriteLine($"TRACE BUILD: {traced} events instrumented");
}

group.Import(true);

// Replacement D3D11 pixel shaders (mod/shaders/<shader>_ps.dxbc, compiled by tools/make_shaders.py): GameMaker
// wraps the DXBC in its own header (uniform table) followed by a string table; the header holds the DXBC size
// and absolute offsets into the string table, which move when the DXBC length changes.
int shadersPatched = 0;
foreach (string dx in Directory.GetFiles(Path.Combine(root, "mod", "shaders"), "*_ps.dxbc"))
{
    string shName = Path.GetFileNameWithoutExtension(dx);
    shName = shName.Substring(0, shName.Length - 3);
    var sh = Data.Shaders.ByName(shName);
    if (sh == null) throw new Exception("no shader " + shName);
    byte[] old = sh.HLSL11_PixelData.Data;
    byte[] neu = File.ReadAllBytes(dx);
    int start = -1;
    for (int k = 0; k + 4 <= old.Length; k++) if (old[k] == 'D' && old[k + 1] == 'X' && old[k + 2] == 'B' && old[k + 3] == 'C') { start = k; break; }
    if (start < 0 || start % 4 != 0) throw new Exception("unexpected shader blob " + shName);
    uint oldSize = BitConverter.ToUInt32(old, start + 24);
    long tailStart = start + oldSize;
    int delta = neu.Length - (int)oldSize;
    var outBytes = new List<byte>();
    for (int k = 0; k < start; k += 4)
    {
        uint v = BitConverter.ToUInt32(old, k);
        if (v == oldSize && k == 24) v = (uint)neu.Length;
        else if (v >= tailStart && v < old.Length) v = (uint)(v + delta);
        outBytes.AddRange(BitConverter.GetBytes(v));
    }
    outBytes.AddRange(neu);
    for (long k = tailStart; k < old.Length; k++) outBytes.Add(old[k]);
    sh.HLSL11_PixelData.Data = outBytes.ToArray();
    shadersPatched++;
}
Console.WriteLine($"shaders: {shadersPatched} pixel shaders replaced");

var coopObj = Data.GameObjects.ByName("obj_coop");
coopObj.Persistent = true;
coopObj.Visible = true;

Console.WriteLine($"COOP BUILD OK: {files} gml files, {hooks} hooks");
