// Builds the co-op data.win: imports mod/gml/*.gml and applies mod/hooks.txt.
// Run via tools/build.sh (UndertaleModCli load <vanilla> -s build.csx -o <out>).
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UndertaleModLib;
using UndertaleModLib.Models;

string root = Environment.GetEnvironmentVariable("COOP_ROOT") ?? @"C:\Users\pasha\zerosievert-coop";
string gmlDir = Path.Combine(root, "mod", "gml");
string hooksFile = Path.Combine(root, "mod", "hooks.txt");

// Extension functions the game never calls itself (e.g. Steam lobby/P2P) have no FUNC entry, so the
// compiler would treat calls to them as variable calls. Declare every one our code uses.
var modText = string.Join("\n", Directory.GetFiles(gmlDir, "*.gml").Select(File.ReadAllText));
int declared = 0;
foreach (var ext in Data.Extensions)
    foreach (var file in ext.Files)
        foreach (var fn in file.Functions)
        {
            string name = fn.Name.Content;
            if (System.Text.RegularExpressions.Regex.IsMatch(modText, @"\b" + name + @"\s*\(") && Data.Functions.ByName(name) == null)
            {
                Data.Functions.EnsureDefined(name, Data.Strings);
                declared++;
            }
        }
Console.WriteLine($"declared {declared} extension functions");

var group = new UndertaleModLib.Compiler.CodeImportGroup(Data)
{
    AutoCreateAssets = true,
    ThrowOnNoOpFindReplace = true
};

// UTMT's compiler does not share #macro across code entries: expand them textually here.
var sources = new Dictionary<string, string>();
var macros = new Dictionary<string, string>();
var macroRx = new System.Text.RegularExpressions.Regex(@"^#macro\s+(\w+)\s+(.+)$", System.Text.RegularExpressions.RegexOptions.Multiline);
// High refresh rate: objects with alarm events for coop_fps.gml. Generated first: a function is only
// visible to code compiled after it.
var alarmIdx = new Dictionary<UndertaleGameObject, SortedSet<uint>>();
foreach (var go in Data.GameObjects)
{
    if (go.Name.Content == "obj_coop") continue;
    foreach (var ev in go.Events[2])
    {
        if (!alarmIdx.ContainsKey(go)) alarmIdx[go] = new SortedSet<uint>();
        alarmIdx[go].Add(ev.EventSubtype);
    }
}
Func<UndertaleGameObject, UndertaleGameObject, bool> isAncestor = (anc, o) =>
{
    for (var p = o.ParentId; p != null && p != o; p = p.ParentId) if (p == anc) return true;
    return false;
};
var tabEntries = new List<string>();
foreach (var go in alarmIdx.Keys)
{
    if (alarmIdx.Keys.Any(a => a != go && isAncestor(a, go))) continue; // covered by with(ancestor)
    var set = new SortedSet<uint>(alarmIdx[go]);
    foreach (var d in alarmIdx.Keys) if (isAncestor(go, d)) set.UnionWith(alarmIdx[d]);
    tabEntries.Add($"[{go.Name.Content}, [{string.Join(", ", set)}]]");
}
sources["gml_GlobalScript_coop_fps_tables"] =
    "// Generated by build.csx: objects with alarm events (top-level ancestors) and the alarm indices they use.\n" +
    "function zs_fps_alarm_table()\n{\n    if (!variable_global_exists(\"zs_fps_alarm_tab\"))\n    {\n        global.zs_fps_alarm_tab = [\n            " +
    string.Join(",\n            ", tabEntries) + "\n        ];\n    }\n    return global.zs_fps_alarm_tab;\n}\n";
Console.WriteLine($"fps: alarm table {tabEntries.Count} objects");
foreach (string file in Directory.GetFiles(gmlDir, "*.gml").OrderBy(f => f))
{
    string text = File.ReadAllText(file).Replace("\r\n", "\n");
    foreach (System.Text.RegularExpressions.Match m in macroRx.Matches(text)) macros[m.Groups[1].Value] = m.Groups[2].Value.Trim();
    sources[Path.GetFileNameWithoutExtension(file)] = macroRx.Replace(text, "");
}
int files = 0;
foreach (var kv in sources)
{
    string text = kv.Value;
    for (int pass = 0; pass < 3; pass++)
        foreach (var m in macros)
            text = System.Text.RegularExpressions.Regex.Replace(text, @"\b" + m.Key + @"\b", m.Value);
    var left = System.Text.RegularExpressions.Regex.Match(text, @"\bCOOP_[A-Z0-9_]+\b");
    if (left.Success) throw new Exception($"unexpanded macro {left.Value} in {kv.Key}");
    group.QueueReplace(kv.Key, text);
    files++;
}

int hooks = 0;
string[] lines = File.ReadAllText(hooksFile).Replace("\r\n", "\n").Split('\n');
for (int i = 0; i < lines.Length; i++)
{
    if (!lines[i].StartsWith("### ")) continue;
    string[] head = lines[i].Substring(4).Split(' ');
    string op = head[0], code = head[1];
    var body = new List<string>();
    int j = i + 1;
    while (j < lines.Length && lines[j] != "<<<END") { body.Add(lines[j]); j++; }
    i = j;
    if (op == "findreplace")
    {
        int f = body.IndexOf("<<<FIND"), r = body.IndexOf("<<<REPLACE");
        string find = string.Join("\n", body.Skip(f + 1).Take(r - f - 1));
        string repl = string.Join("\n", body.Skip(r + 1));
        group.QueueFindReplace(code, find, repl, true);
    }
    else if (op == "prepend") group.QueuePrepend(code, string.Join("\n", body));
    else if (op == "append") group.QueueAppend(code, string.Join("\n", body));
    else throw new Exception("unknown hook op " + op);
    hooks++;
}

// High refresh rate (coop_fps.gml): the game's logic events exit on render-only frames. Alarms are not
// guarded (that would lose them) - they are held by obj_coop through the generated table (top of this file).
var guardRx = new System.Text.RegularExpressions.Regex(@"^gml_Object_(.+)_(Step_[012]|Collision_.+|Keyboard_\d+|KeyPress_\d+|KeyRelease_\d+|Mouse_\d+|Other_(0|1|4\d|5\d))$");
int guarded = 0;
foreach (var code in Data.Code.ToList())
{
    if (code.ParentEntry != null) continue;
    string cname = code.Name.Content;
    var gm = guardRx.Match(cname);
    if (!gm.Success || gm.Groups[1].Value == "obj_coop" || sources.ContainsKey(cname)) continue;
    group.QueuePrepend(cname, "if (global.zs_rfq && zs_rf_q()) exit;");
    guarded++;
}
Console.WriteLine($"fps: guarded {guarded} logic events");

group.Import(true);

var coopObj = Data.GameObjects.ByName("obj_coop");
coopObj.Persistent = true;
coopObj.Visible = true;

Console.WriteLine($"COOP BUILD OK: {files} gml files, {hooks} hooks");
